#!/usr/bin/env python3
"""
ConvertCookie Tool - Desktop Version v2.0
Chuyển đổi cookie Facebook sang nhiều định dạng
"""

import os
import sys
import json
import shutil
import tkinter as tk
from tkinter import ttk, filedialog, messagebox
from datetime import datetime

# ==================== COOKIE CONVERTER ====================

class CookieConverter:
    def __init__(self):
        self.cookies_data = []
        
    def parse_cookie_line(self, line):
        line = line.strip()
        if not line:
            return None
            
        password = ""
        if "|" in line:
            parts = line.rsplit("|", 1)
            cookie_str = parts[0].strip()
            password = parts[1].strip() if len(parts) > 1 else ""
        else:
            cookie_str = line
            
        cookies = {}
        c_user = None
        
        for part in cookie_str.split(";"):
            part = part.strip()
            if "=" in part:
                key, value = part.split("=", 1)
                cookies[key.strip()] = value.strip()
                if key.strip() == "c_user":
                    c_user = value.strip()
                    
        if not c_user:
            return None
            
        return {"c_user": c_user, "cookies": cookies, "cookie_string": cookie_str, "password": password}
    
    def to_netscape_format(self, cookies, domain=".facebook.com"):
        lines = ["# Netscape HTTP Cookie File", "# Generated by ConvertCookie Tool", ""]
        expire_time = str(int(datetime.now().timestamp()) + 365 * 24 * 60 * 60)
        for name, value in cookies.items():
            lines.append(f"{domain}\tTRUE\t/\tTRUE\t{expire_time}\t{name}\t{value}")
        return "\n".join(lines)
    
    def to_json_format(self, cookies, domain=".facebook.com"):
        expire_time = int(datetime.now().timestamp()) + 365 * 24 * 60 * 60
        return json.dumps([{"domain": domain, "expirationDate": expire_time, "httpOnly": True,
                           "name": n, "path": "/", "secure": True, "value": v} for n, v in cookies.items()], indent=2)
    
    def process_input_file(self, input_path):
        self.cookies_data = []
        with open(input_path, "r", encoding="utf-8") as f:
            for line in f:
                parsed = self.parse_cookie_line(line)
                if parsed:
                    self.cookies_data.append(parsed)
        return len(self.cookies_data)
    
    def export_all(self, input_path, output_base, add_folder=None):
        results = {"success": 0, "failed": 0, "output_dir": "", "netscape_file": "", "json_file": ""}
        
        timestamp = datetime.now().strftime("%H-%M-%S_%d-%m-%Y")
        output_dir = os.path.join(output_base, f"{timestamp}_({len(self.cookies_data)})")
        os.makedirs(output_dir, exist_ok=True)
        results["output_dir"] = output_dir
        
        input_dir = os.path.dirname(input_path)
        all_netscape = ["# Netscape HTTP Cookie File", ""]
        all_json = []
        expire = int(datetime.now().timestamp()) + 365 * 24 * 60 * 60
        
        for data in self.cookies_data:
            try:
                c_user, cookies, password = data["c_user"], data["cookies"], data["password"]
                user_dir = os.path.join(output_dir, c_user)
                os.makedirs(user_dir, exist_ok=True)
                
                with open(os.path.join(user_dir, "Cookie_Headerstring.txt"), "w") as f:
                    f.write(self.to_netscape_format(cookies))
                with open(os.path.join(user_dir, "Cookie.json"), "w") as f:
                    f.write(self.to_json_format(cookies))
                with open(os.path.join(user_dir, "Password.txt"), "w") as f:
                    f.write(password)
                
                if add_folder and os.path.exists(add_folder):
                    for item in os.listdir(add_folder):
                        src, dst = os.path.join(add_folder, item), os.path.join(user_dir, item)
                        shutil.copytree(src, dst, dirs_exist_ok=True) if os.path.isdir(src) else shutil.copy2(src, dst)
                
                for name, value in cookies.items():
                    all_netscape.append(f".facebook.com\tTRUE\t/\tTRUE\t{expire}\t{name}\t{value}")
                all_json.append({"c_user": c_user, "password": password, 
                                "cookies": [{"name": k, "value": v} for k, v in cookies.items()]})
                results["success"] += 1
            except:
                results["failed"] += 1
        
        with open(os.path.join(input_dir, "cookies_netscape.txt"), "w") as f:
            f.write("\n".join(all_netscape))
        with open(os.path.join(input_dir, "cookies.json"), "w") as f:
            json.dump(all_json, f, indent=2)
        results["netscape_file"], results["json_file"] = "cookies_netscape.txt", "cookies.json"
        return results


# ==================== LIGHT THEME UI ====================

class Style:
    BG = "#f5f5f5"
    BG_CARD = "#ffffff"
    ACCENT = "#2196F3"
    ACCENT_HOVER = "#1976D2"
    SUCCESS = "#4CAF50"
    TEXT = "#333333"
    TEXT_SECONDARY = "#666666"
    BORDER = "#e0e0e0"


class CookieConverterApp:
    def __init__(self, root):
        self.root = root
        self.root.title("ConvertCookie Tool")
        self.root.geometry("560x420")
        self.root.configure(bg=Style.BG)
        self.root.resizable(True, True)
        
        self.converter = CookieConverter()
        self.base_dir = os.path.dirname(sys.executable) if getattr(sys, 'frozen', False) else os.path.dirname(os.path.abspath(__file__))
        self.input_dir = os.path.join(self.base_dir, "input")
        self.output_dir = os.path.join(self.base_dir, "output")
        self.add_dir = os.path.join(self.input_dir, "add")
        
        for d in [self.input_dir, self.output_dir, self.add_dir]:
            os.makedirs(d, exist_ok=True)
        
        self.setup_ui()
        
    def setup_ui(self):
        main = tk.Frame(self.root, bg=Style.BG, padx=12, pady=10)
        main.pack(fill=tk.BOTH, expand=True)
        
        # Header
        tk.Label(main, text="🍪 ConvertCookie", font=("Segoe UI", 13, "bold"), 
                bg=Style.BG, fg=Style.TEXT).pack()
        tk.Label(main, text="Chuyển đổi cookie sang Netscape & JSON", 
                font=("Segoe UI", 8), bg=Style.BG, fg=Style.TEXT_SECONDARY).pack(pady=(0, 8))
        
        # Input Frame
        input_frame = tk.LabelFrame(main, text=" Input ", font=("Segoe UI", 8, "bold"),
                                   bg=Style.BG_CARD, fg=Style.ACCENT, padx=8, pady=6)
        input_frame.pack(fill=tk.X, pady=4)
        
        file_row = tk.Frame(input_frame, bg=Style.BG_CARD)
        file_row.pack(fill=tk.X)
        
        self.input_var = tk.StringVar()
        tk.Entry(file_row, textvariable=self.input_var, font=("Consolas", 8),
                bg=Style.BG, fg=Style.TEXT, relief="flat", bd=3).pack(side=tk.LEFT, fill=tk.X, expand=True, padx=(0, 4))
        
        tk.Button(file_row, text="Chọn", command=self.browse_file, font=("Segoe UI", 8),
                 bg=Style.BG, fg=Style.TEXT, relief="flat", padx=8, cursor="hand2").pack(side=tk.RIGHT)
        
        # Buttons
        btn_frame = tk.Frame(main, bg=Style.BG)
        btn_frame.pack(fill=tk.X, pady=8)
        
        tk.Button(btn_frame, text="⚡ Export Nhanh", command=self.quick_export,
                 bg=Style.ACCENT, fg="white", font=("Segoe UI", 9, "bold"),
                 relief="flat", padx=12, pady=4, cursor="hand2").pack(side=tk.LEFT, padx=2, expand=True, fill=tk.X)
        
        tk.Button(btn_frame, text="🔄 Chuyển đổi", command=self.convert_cookies,
                 bg=Style.SUCCESS, fg="white", font=("Segoe UI", 9),
                 relief="flat", padx=12, pady=4, cursor="hand2").pack(side=tk.LEFT, padx=2, expand=True, fill=tk.X)
        
        tk.Button(btn_frame, text="📂 Mở Output", command=self.open_output,
                 bg=Style.BORDER, fg=Style.TEXT, font=("Segoe UI", 9),
                 relief="flat", padx=12, pady=4, cursor="hand2").pack(side=tk.LEFT, padx=2, expand=True, fill=tk.X)
        
        # Log Frame
        log_frame = tk.LabelFrame(main, text=" Log ", font=("Segoe UI", 8, "bold"),
                                 bg=Style.BG_CARD, fg=Style.ACCENT, padx=8, pady=6)
        log_frame.pack(fill=tk.BOTH, expand=True, pady=4)
        
        self.log_text = tk.Text(log_frame, height=10, font=("Consolas", 8),
                               bg=Style.BG, fg=Style.TEXT, relief="flat", bd=3)
        self.log_text.pack(fill=tk.BOTH, expand=True)
        
        scrollbar = tk.Scrollbar(self.log_text, command=self.log_text.yview)
        scrollbar.pack(side=tk.RIGHT, fill=tk.Y)
        self.log_text.config(yscrollcommand=scrollbar.set)
        
        # Status
        self.status_var = tk.StringVar(value="Sẵn sàng")
        tk.Label(main, textvariable=self.status_var, font=("Segoe UI", 7),
                bg=Style.BORDER, fg=Style.TEXT_SECONDARY, anchor="w", padx=6, pady=2).pack(fill=tk.X, pady=(4, 0))
        
        self.log("✅ Khởi tạo thành công")
    
    def log(self, msg):
        self.log_text.insert(tk.END, f"[{datetime.now().strftime('%H:%M:%S')}] {msg}\n")
        self.log_text.see(tk.END)
        
    def browse_file(self):
        path = filedialog.askopenfilename(title="Chọn file cookie", initialdir=self.input_dir,
                                         filetypes=[("Text", "*.txt"), ("All", "*.*")])
        if path:
            self.input_var.set(path)
            self.log(f"📄 {os.path.basename(path)}")
            
    def quick_export(self):
        default = os.path.join(self.input_dir, "input.txt")
        if os.path.exists(default):
            self.input_var.set(default)
            self.convert_cookies()
        else:
            messagebox.showerror("Lỗi", f"Không tìm thấy: {default}")
            
    def convert_cookies(self):
        path = self.input_var.get()
        if not path or not os.path.exists(path):
            messagebox.showerror("Lỗi", "Chọn file input!")
            return
            
        self.log("🔄 Đang xử lý...")
        self.status_var.set("Đang xử lý...")
        self.root.update()
        
        try:
            count = self.converter.process_input_file(path)
            self.log(f"📊 Tìm thấy {count} cookie")
            
            if count == 0:
                self.log("⚠️ Không có cookie hợp lệ!")
                self.status_var.set("Không có cookie")
                return
            
            add = self.add_dir if os.path.exists(self.add_dir) and os.listdir(self.add_dir) else None
            results = self.converter.export_all(path, self.output_dir, add)
            
            # Log success instead of modal
            self.log("=" * 40)
            self.log(f"✅ THÀNH CÔNG: {results['success']} cookies")
            self.log(f"📁 Output: {os.path.basename(results['output_dir'])}")
            self.log(f"📄 cookies_netscape.txt")
            self.log(f"📄 cookies.json")
            self.log("=" * 40)
            
            self.status_var.set(f"✅ Xong! {results['success']} cookies")
                
        except Exception as e:
            self.log(f"❌ Lỗi: {str(e)}")
            self.status_var.set("Lỗi!")
            
    def open_output(self):
        if os.path.exists(self.output_dir):
            if sys.platform == "win32":
                os.startfile(self.output_dir)
            else:
                os.system(f'xdg-open "{self.output_dir}"' if sys.platform != "darwin" else f'open "{self.output_dir}"')


def main():
    root = tk.Tk()
    CookieConverterApp(root)
    root.mainloop()


if __name__ == "__main__":
    main()
